[package]
name = "nucleo-h745zi"
version = "0.1.0"
authors = ["Antoine van Gelder <antoine@flowdsp.io>"]
edition = "2018"
license = "AGPL-3.0-or-later"
description = "A board support package for the nucleo-h745zi"
repository = "https://github.com/antoinevg/nucleo-h745zi"
documentation = "https://github.com/antoinevg/nucleo-h745zi/wiki"
categories = [
    "embedded",
    "hardware-support",
    "no-std",
]
keywords = [
    "cortex-m",
    "bsp",
    "stm32h7xx",
    "stm32h745",
]
readme = "README.md"

[package.metadata.docs.rs]
features = [ ]
targets = ["thumbv7em-none-eabihf"]


# - dependencies --------------------------------------------------------------

[dependencies]
cortex-m = "^0.6.2"
cortex-m-rt = { version = "^0.6.12" }
embedded-timeout-macros = { version = "0.3.0" }
void = { version = "1.0.2", default-features = false }
heapless = { version = "0.5.6", default_features = true }
nb = "1.0.0"

[dependencies.stm32h7xx-hal]
features = [ "stm32h747cm7", "rt", "ethernet" ]
#version = "0.8.0"
git = "https://github.com/stm32-rs/stm32h7xx-hal.git"
branch = "master"

# - optional dependencies -----------------------------------------------------

[dependencies.smoltcp]
version = "0.7.0"
#path = "../mirrors/smoltcp.git"
default-features = false
features = ["ethernet", "proto-ipv4", "proto-ipv6", "socket-raw", "socket-udp"]
#optional = true

# - dependencies for examples -------------------------------------------------

[dependencies.jacktrip]
path = "../jacktrip_rs.git"
default-features = false
optional = true

# - dev dependencies ----------------------------------------------------------

[dev-dependencies]
cortex-m-semihosting = { version = "0.3.5" }
panic-semihosting = { version = "0.5.3" }
panic-itm = { version = "0.4.2" }


# - features ------------------------------------------------------------------

[features]
default = []
itm = []


# - profiles ------------------------------------------------------------------

[profile.dev]
#opt-level = 1  # default: 0
opt-level = "s" # optimize for binary size
#debug = true              # default: true
#debug-assertions = false  # default: true
#overflow-checks = false   # default: true
#lto = "off"               # default: false
#panic = "unwind"          # default: "unwind"
#incremental = false       # default: true

[profile.release]
debug = true
#opt-level = "s" #  optimize for binary size


# - examples ------------------------------------------------------------------

[[example]]
name = "blinky_bsp"
required-features = []

[[example]]
name = "blinky_hal"
required-features = []

[[example]]
name = "blinky_pac"
required-features = []

#[[example]]
#name = "button"
#required-features = []

[[example]]
name = "ethernet"
required-features = []

[[example]]
name = "itm"
required-features = [ "itm" ]

[[example]]
name = "jacktrip"
required-features = [ "jacktrip" ]
