[package]
name = "nucleo-h745zi"
version = "0.1.0"
authors = ["Antoine van Gelder <antoine@flowdsp.io>"]
edition = "2018"
license = "AGPL-3.0-or-later"
description = "A board support package for the nucleo-h745zi"
repository = "https://github.com/antoinevg/nucleo-h745zi"
documentation = "https://github.com/antoinevg/nucleo-h745zi/wiki"
categories = [
    "embedded",
    "hardware-support",
    "no-std",
]
keywords = [
    "cortex-m",
    "bsp",
    "stm32h7xx",
    "stm32h745",
]
readme = "README.md"

[package.metadata.docs.rs]
features = [ ]
targets = ["thumbv7em-none-eabihf"]


# - dependencies --------------------------------------------------------------

[dependencies]
cortex-m = "^0.6.2"
cortex-m-rt = { version = "^0.6.12", features = ["device"] }
cty = "0.2.1"

# move to dev dependencies
panic-semihosting = { version = "0.5.3" }
cortex-m-semihosting = { version = "0.3.5" }

# - select version of stm32h7xx-hal to use

[dependencies.stm32h7xx-hal]
features = [ "stm32h747cm7", "rt" ]
version = "0.8.0"




# - optional dependencies used by examples

[dependencies.num]
version = "0.3.1"
default-features = false
features = [ "libm" ]
optional = true

[dependencies.num-derive]
version = "0.3.3"
default-features = false
optional = true

[dependencies.num-traits]
version = "0.2.14"
default-features = false
optional = true


# - dev dependencies ----------------------------------------------------------

[dev-dependencies]


# - features ------------------------------------------------------------------

[features]
default = []
uses_num = [ "num", "num-derive", "num-traits" ]


# - profiles ------------------------------------------------------------------

[profile.dev]
debug = true
incremental = false
opt-level = "s" # optimize for binary size
#opt-level = 1
#opt-level = 0

[profile.release]
debug = true
opt-level = "s" #  optimize for binary size


# - examples ------------------------------------------------------------------

[[example]]
name = "blinky_pac"
required-features = []

[[example]]
name = "blinky_hal"
required-features = []

[[example]]
name = "blinky_bsp"
required-features = []

[[example]]
name = "button"
required-features = []
